# Generated by Django 5.0.6 on 2024-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
