# Generated by Django 5.0.6 on 2024-05-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_alter_usertype_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usertype',
        ),
    ]
