# Generated by Django 5.0.6 on 2024-05-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usertype',
        ),
    ]
